project:
  type: website
  output-dir: docs

website:
  title: "matiaslibuy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: urgent-clinics.qmd
        text: Urgent Clinics impact in healthcare networks
      - href: physician-impact.qmd
        text: Emergency medicine physician impact in emergency department timeframes
      - href: bed-estimation.qmd
        text: Service/bed model estimation for Chile
  page-footer:
    left: "© 2025 Matías Libuy Ríos"
    right:
      - icon: envelope
        href: mailto:matiaslibuy@uchile.cl

format:
  html:
    theme: default
    toc: true
    math: mathjax